services:
  - type: web
    name: crypto-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn crypto_predictor.wsgi --log-file -
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com,127.0.0.1,localhost
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: SECRET_KEY
        generateValue: true
